### ISSUE TITLE
Observer needs to check if holder is an HTMLElement before calling querySelector

### ISSUE THREAD

**Issue by oliverw** [kommitters/editorjs-undo#18]
Calling `querySelector` [here](https://github.com/kommitters/editorjs-undo/blob/master/src/observer.js#L36) results in an uncessary crash in case the Editor was initialized from a HTMLElement reference instead of a selector.

Recommended fix:
```
const target = this.holder instanceof HTMLElement ? this.holder : document.querySelector(`#${this.holder}`);
```

**Comment by Jmzp** [comment]
@oliverw ttanks for the recommendation, this was fixed and it is in develop branch.

https://github.com/kommitters/editorjs-undo/commit/72d2221fe5706854af9c977725e18b78165bab32

**Comment by lamualfa** [comment]
@oliverw Just clarifying, If you need the newer version with solved error in your project, just install it from Github Repository with command below:

**With NPM**:

`npm install git+https://github.com/kommitters/editorjs-undo.git\#develop`

**or with Yarn**

`yarn add https://github.com/kommitters/editorjs-undo.git#develop`

**Comment by lamualfa** [comment]
@Jmzp Please re-open this Issue. I already installed newer version of this library from `develop` branch. and error still occur.

**The Error**

![image](https://user-images.githubusercontent.com/39755201/97809173-f9b89980-1c9d-11eb-9b3c-32e0c183be76.png)
