### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'holder')

### ISSUE THREAD

**Issue by SergeyRose** [kommitters/editorjs-undo#66]
```
const Demo2 = () => {
  const edjsParser = edjsHTML();

  const handleReady = (editor) => {
    new Undo({ editor });
    new DragDrop(editor);
  };

  const handleChange = (api, newData) => console.log(newData, edjsParser.parse(newData), 'Something is changing!!');

  return (
    <EditorJs
      tools={EDITOR_JS_TOOLS}
      onReady={handleReady}
      onChange={handleChange}
    />
  );
};
```

Steps to reproduce
1. Type something
2. Ctrl + Z
3. click the editor

    "editorjs-undo": "^0.3.0",
    "react-editor-js": "^1.10.0",

**Comment by MarioRodriguezS** [comment]
@SergeyRose Hi there!
Thanks a lot for report the issue, 
It was solved, and the solution will be updated in our v1.0 soon. 

Best,
Mario

**Comment by ErriourRU** [comment]
Hey! This error is still appearing when I'm trying to use several EditorJS instances...

**Comment by MarioRodriguezS** [comment]
> Hey! This error is still appearing when I'm trying to use several EditorJS instances...

@ErriourRU, thanks for the comment
If you use several EditorJS instance, you have to specify the respective instance in undo with the key 'editor' as following:  
`const editor = new EditorJS({
   onReady: () => {
    new Undo({ editor });
  },`
`const editor2 = new EditorJS({
   onReady: () => {
    new Undo({ editor: editor2 });
  },`
`...`

I hope that I have answered your issue.
Best,
Mario

**Comment by khanakia** [comment]
I am also having the same issue. Any update ?
